### ISSUE TITLE
integrate codecov and travis

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/makeDataCube#16]
@PabRod : can you help with integrating codecov and travis in Github? I believe that I don't have permissions to add the makeDataCube repository. Thanks!

**Comment by PabRod** [comment]
Solved e93be7bfba7b0cf731cabed0c47c75804b7098f8

It seems to be a problem related to the existence of two Travis: .org and .com.

The .com one is the recommended one for new projects.
