### ISSUE TITLE
Environment-dependent line in vignette

### ISSUE THREAD

**Issue by PabRod** [RETURN-project/makeDataCube#20]
The first time [this line](https://github.com/RETURN-project/makeDataCube/blob/34abad14ca53216058c48307669c1455569da443/vignettes/make_Landsat_cube.Rmd#L102) of `vignettes/make_Landsat_cube.Rmd` is run:

```r
LSscenes <- dllLS(l1folder, queuefolder, queuefile, tmpfolder, landsatlogfile, ext, starttime, endtime, sensors, tiers, cld)
```

it downloads a set of files and populates the variable `LSscenes`. If executed again (when the files have already been downloaded), `LSscenes` returns an empty list. 

This environment-dependent behavior is dangerous, and it may cause bugs.

**Comment by PabRod** [comment]
By digging a bit into `dllLS`, we find that the output assignation happens in [this line](https://github.com/RETURN-project/makeDataCube/blob/34abad14ca53216058c48307669c1455569da443/R/Landsat.R#L27) of `R/Landsat.R`:

```r
scenes <- dllLandsat(queuefolder, queuefile, tmpfolder, logfile, ext, starttime, endtime, sensors, tiers, cld)
```

The `dllLandsat` function is available in [`inst/python/dllLandsat.py`](https://github.com/RETURN-project/makeDataCube/blob/master/inst/python/dllLandsat.py).

**Comment by PabRod** [comment]
@wanda: [it seems](https://github.com/RETURN-project/makeDataCube/commits/master/inst/python/dllLandsat.py) that `dllLandsat.py` has been copied directly from another source. Can you give me some context?

Thanks in advance!

**Comment by wandadk** [comment]
`dllLandsat.py` only downloads data that haven't been added to the queue already (lines 30-35 in `dllLandsat.py`). This was done to prevent that we download data if it is not really needed (since it was already added to the cube).

I wrote `dllLandsat.py` myself (inspired by these [examples](https://pypi.org/project/pylandsat/)), but added it the the `/inst` folder, so R recognizes the python function when building the R package.

**Comment by PabRod** [comment]
I see. Please check if [this pull request](https://github.com/RETURN-project/makeDataCube/pulls) works for you.

It contains minimal changes, actually, it is a one-liner. I haven't changed the way the data is managed, so the downloads will still happen only if needed. The only change is the output: it will be **always** the list of files, regardless of the fact of them having been downloaded or not.

**Comment by wandadk** [comment]
Thanks! 

The list of scenes is used in the vignette to add the scenes to the queue and process them to a level-2 product (line 131 in [vignette](https://github.com/RETURN-project/makeDataCube/blob/master/vignettes/make_Landsat_cube.Rmd#L131)). 

`Landsat2L2(paramfolder, paramfile, l2folder, LSscenes, logfolder, Sskiplogfile, Ssuccesslogfile, Smissionlogfile, Sotherlogfile)`

Although I did not test it, I'm afraid that providing the total list of scenes will result in errors. Maybe a solution could be to output both the total list of scenes and also the list of scenes that have been downloaded. The latter list can then be used as input for the Landsat2L2 function.

**Comment by PabRod** [comment]
I'll consider this closed after the accepted pull request.
