### ISSUE TITLE
Minor bug in dllWVP function

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/makeDataCube#26]
The dllWVP function was missing an input parameter (the end date for which WVP data need to be supplied), which is fixed now in this [fix](https://github.com/RETURN-project/makeDataCube/blob/13ec36d61659412afeb95bc9f85da8e0b6540067/R/WVP.R#L10) .

**Comment by PabRod** [comment]
Thanks! 

I think it will be better to fix it in `master` and merge it afterward to the branch.

I'll take care of that.

**Comment by PabRod** [comment]
Reverted commit to `feature/FORCEcsd` : https://github.com/RETURN-project/makeDataCube/commit/2d3bee06deea239e0d58ea00c42bcd97c4464451

**Comment by PabRod** [comment]
Cherry-picked commit from `feature/FORCEcsd` to `master` : https://github.com/RETURN-project/makeDataCube/commit/b93d93aa58c060be3779818602a765318a3abfdc

Required:

- Solving a conflict in the vignette
- Fixing a typo in the function call

**Comment by PabRod** [comment]
Synchronize the fix with branch `feature/FORCEcsd` : https://github.com/RETURN-project/makeDataCube/commit/d14ac77f8e2f0552e2d1da0b81783881a2edda17

And with branch `feature/snakemake` : https://github.com/RETURN-project/makeDataCube/commit/f7b3b3da1219c2894d6c2fa734c2393cfe0bbceb
