### ISSUE TITLE
Bug in Landsat / getScenes chunk

### ISSUE THREAD

**Issue by PabRod** [RETURN-project/makeDataCube#31]
The chunk is crashing. The error can be tracked down to:

https://github.com/RETURN-project/makeDataCube/blob/b512a87726c2879042aa789c297c44737c274569/R/General.R#L193

https://github.com/RETURN-project/makeDataCube/blob/b512a87726c2879042aa789c297c44737c274569/R/General.R#L232

```sh
Error in writeOGR(spdf, dsn = ofile, layer = oname, driver = "ESRI Shapefile") : 
  object 'oname' not found
```

**Comment by PabRod** [comment]
This issue is triggering a broken build warning in our Continuous Integration system.

**Comment by wandadk** [comment]
Hi Pablo,

Thanks for notifying! It is a bit weird, because this bug is not present
(anymore) in my local version (also not after pulling). I will fix it
online in github.

Best,
Wanda

Op do 21 jan. 2021 om 10:30 schreef Pablo Rodríguez-Sánchez <
notifications@github.com>:

**Comment by PabRod** [comment]
Related commit: 6b7f7dcc3eea8780dcbe5f9fa55627590a85ad5b

**Comment by PabRod** [comment]
Still failing. My guess is that the parameter `metafolder` is not defined in vignette.

**Comment by wandadk** [comment]
I added the metafolder to the tree structure now

**Comment by PabRod** [comment]
Thanks.

I am still having a problem (`force-level1-csd: command not found`), but I think I just have to upgrade FORCE. 

I'll close this.

**Comment by wandadk** [comment]
You can also download the hi.sif file from Spider to get a more recent
FORCE version.

Op do 21 jan. 2021 om 16:10 schreef Pablo Rodríguez-Sánchez <
notifications@github.com>:
