### ISSUE TITLE
Problem installing package in singularity container

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/makeDataCube#39]
While installing the `makeDateCube`  package in a singularity container (Ubuntu bionic), I received the following error message:

```
Error : (converted from warning) /tmp/RtmpW3UQTX/R.INSTALL6ec56c383c36/makeDataCube/man/systemf.Rd:12: unknown macro '\item'
ERROR: installing Rd objects failed for package 'makeDataCube'
* removing '/usr/local/lib/R/site-library/makeDataCube'
Error: Failed to install 'makeDataCube' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpV4187b/file6a9e77dc2dac/makeDataCube_0.1.0.tar.gz' had non-zero exit status

```
The definition file is available [here](https://github.com/RETURN-project/Tools/blob/master/singularity/k.def).

**Comment by PabRod** [comment]
Wow, that was a subtle one.

Apparently, `roxygen2` doesn't handle well percentage symbols. More info [here](https://stackoverflow.com/questions/39670646/r-github-package-w-devtools-warning-unknown-macro-item).
