### ISSUE TITLE
Bug parallel download

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/makeDataCube#40]
I tried to download Landsat data using the parallel download option on Spider. I requested a download of about 1.27 TB of data using 7 time splits, yet only 129 GB of data was actually downloaded. It looks like only one time slice succeeded (inspecting the downloaded data shows a limited range of downloaded years). While checking the job outputs, I noticed a bug was reported (this bug was mentioned several times):

`sed: can't read /project/return/Data/UpscaleRecovery/force_tst1/level1/csd_metadata_2021-04-12T13-36-34.txt: No such file or directory`

@PabRod : Is this related to the fix you pushed to the FORCE development branch? I installed the development branch of FORCE in a singularity container (starting from a [docker container](https://hub.docker.com/r/davidfrantz/force)), but maybe something still went wrong here.

Head of the definition file of the singularity container:

```
Bootstrap: docker
From: davidfrantz/force:dev
```

Thanks!

**Comment by PabRod** [comment]
I don't think so. [My fix](https://github.com/davidfrantz/force/commit/a190f83b62c6088d6d480a0602e616014de2b95f) affects another folder (`l1csd-temp_xxxxxx`).

## Problem

The problem seems to be in this line:

https://github.com/davidfrantz/force/blob/2dbafd248c5b75b1cbdd23c11755aa0327a1e133/bash/force-level1-csd.sh#L412

## Solution

In the next days:

1. I'll fork FORCE and patch this. 
2. I'll offer davidfrantz a pull request.
3. I'll try to make our fork installable through Docker hub.

**Comment by PabRod** [comment]
@wandadk, please try again using this Docker Hub image:

```
Bootstrap: docker
From: pabrod/force:latest
```

**Comment by wandadk** [comment]
Hi Pablo,

Good news: I tested the download using the Docker Hub image and was able to download data in parallel.

**Comment by wandadk** [comment]
@PabRod: I tried to process data using a singularity image that was built upon the Docker Hub Image, but I'm running into some issues. 

Currently gdal version 2.2.3 is available through the Docker Hub Image. I need to update `gdal` in order to install `rgdal` (which is a dependency of the `makeDateCube` package). Yet, by running `apt-get -y install gdal-bin  libgdal-dev`, I am breaking FORCE. 

For example, if I run `force-parameter` after the gdal installation, I get the error 
`force-parameter: error while loading shared libraries: libgdal.so.20: cannot open shared object file: No such file or directory
`
Hence, I wonder if it would be feasible to install a recent gdal version (>=3) before installing FORCE in the Docker Hub Image? For instance:
```
gdalinfo --version
GDAL 3.0.4, released 2020/01/28
```

**Comment by PabRod** [comment]
Hi @wandadk,

In principle that should be possible, and even easy:

1. Fork and clone FORCE.
2. Edit `Dockerfile` and add the installation lines you want.
3. Execute `docker build -t <id> .`. Details [here](https://force-eo.readthedocs.io/en/latest/setup/docker.html#for-developers-local-build).
4. Publish your new docker image by pushing it to Docker Hub.

I am trying to do it, but I am finding an annoying problem. When I run any `apt-get` command inside `davidfrantz/base` Docker image, even with `sudo` privileges, I find this error:

```sh
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
```

I'll keep you posted.

**Comment by wandadk** [comment]
Ok, thanks. If adjusting the Docker Hub image would be too difficult, I could also try to install FORCE and dependencies directly in a singularity container.

**Comment by PabRod** [comment]
That's a possibility, indeed. The only tweak you'll need is to install from source [my forked version](https://github.com/PabRod/force).

**Comment by PabRod** [comment]
I've created a [pull request](https://github.com/davidfrantz/force/pull/87) in the official `FORCE` repo.

**Comment by wandadk** [comment]
> 
> 
> That's a possibility, indeed. The only tweak you'll need is to install from source [my forked version](https://github.com/PabRod/force).

Ok, I'll install directly in a singularity container, that might be the easiest and fastest solution. Particularly because I will face the same problem when using the original Docker Hub image (generated by David Frantz).

**Comment by wandadk** [comment]
I successfully installed FORCE and the makeDataCube package in a singularity container. I started from the Docker Hub image of David Frantz to avoid having to install all FORCE dependencies, then updated gdal, reinstalled FORCE (the fork), and installed all R packages. You can find the definition file [here](https://github.com/RETURN-project/Tools/blob/master/singularity/k.def).

**Comment by PabRod** [comment]
Wow! Thank you @wandadk!

**Comment by PabRod** [comment]
> I've created a [pull request](https://github.com/davidfrantz/force/pull/87) in the official `FORCE` repo.

My pull request has been incorporated to FORCE since commit https://github.com/davidfrantz/force/commit/f6b9d48ec037628468c7925d0bc73c20d17fa059
